name: hotel_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #icon  
  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #chached image
  cached_network_image: ^3.2.3

  #router
  auto_route: ^7.8.0

  #make request to api
  retrofit: '>=4.0.0 <5.0.0'



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^4.4.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
